version: 2.1

jobs:
  check:
    docker:
      - image: circleci/buildpack-deps:sid
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t aws-cli-toolbox .
      - run:
          name: Test Docker image
          command: |
            docker run --rm -it aws-cli-toolbox aws --version

workflows:
  build:
    jobs:
      - check
